version: '3'
services:
  nginx_lambda:
    hostname: nginx_lambda
    container_name: nginx_lambda
    image: nginx_lambda
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./service/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./core:/etc/nginx/lambda
    ports:
      - "80:80"
      - "8080:8080"
    env_file:
      - settings.test
