version: '3'
services:
  nginx_lambda_02:
    hostname: nginx_lambda_02
    container_name: nginx_lambda_02
    image: nginx_lambda_02
    build:
      context: ../../
      # Enable this when using NGINX OSS
      dockerfile: ./docker/Dockerfile.oss
      
      # Enable this when using NGINX Plus
      # dockerfile: ./docker/Dockerfile.plus
    volumes:
      - ../../examples/02-one-lambda-function-arn/:/etc/nginx/conf.d/
      - ../../core:/etc/nginx/aws
    ports:
      - "82:80"
    env_file:
      - ../../settings.test
