version: '3'
services:
  nginx_lambda_03:
    hostname: nginx_lambda_03
    container_name: nginx_lambda_03
    image: nginx_lambda_03
    build:
      context: ../../
      # Enable this when using NGINX OSS
      dockerfile: ./docker/Dockerfile.oss
      
      # Enable this when using NGINX Plus
      # dockerfile: ./docker/Dockerfile.plus
    volumes:
      - ../../examples/03-one-lambda-function-url/:/etc/nginx/conf.d/
      - ../../core:/etc/nginx/aws
    ports:
      - "83:80"
    env_file:
      - ../../settings.test
