FROM nginx

LABEL maintainer="Shawn"

RUN mkdir -p /etc/nginx/aws     && \
    mkdir -p /etc/nginx/conf.d  

RUN chmod -R 644 /etc/nginx
RUN chmod -R 644 /etc/nginx/aws
RUN chmod -R 644 /etc/nginx/conf.d

COPY  common/lambda-core/*          /etc/nginx/aws/
COPY  common/etc/nginx/nginx.conf   /etc/nginx/

STOPSIGNAL SIGTERM
CMD ["nginx", "-g", "daemon off;"]
