version: '3'
services:
  nginx_lambda_gateway_01:
    hostname: nginx_lambda_gateway_01
    container_name: nginx_lambda_gateway_01
    image: nginx_lambda_gateway_01
    build:
      context: ../../
      # Enable this when using NGINX OSS
      dockerfile: ./docker/Dockerfile.oss
      
      # Enable this when using NGINX Plus
      # dockerfile: ./docker/Dockerfile.plus
    volumes:
      - ../../examples/01-all-lambda-function-arns/:/etc/nginx/conf.d/
      - ../../common/lambda-core:/etc/nginx/serverless
    ports:
      - "80:80"
    env_file:
      - ../../settings.env
